using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;

[assembly: AssemblyTitle("LLBLGen Pro Dynamic Query Engine for Google Cloud Spanner")]
[assembly: AssemblyDescription("Dynamic Query Engine to use within code generated by LLBLGen Pro, to target Google Cloud Spanner instances")]
[assembly: AssemblyConfiguration(".NET Standard 2.0+ / .NET 4.5.2 or higher")]

[assembly: AssemblyCompany("Solutions Design bv")]
[assembly: AssemblyProduct("LLBLGen Pro")]
[assembly: AssemblyCopyright("(c)2002-2021 Solutions Design. All rights reserved.")]
[assembly: AssemblyTrademark("LLBLGen and LLBLGen Pro are trademarks of Solutions Design.")]
[assembly: AssemblyCulture("")]
[assembly: CLSCompliant(true)]

[assembly: AllowPartiallyTrustedCallers()]

[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyKeyFile("..\\LLBLGenProSpannerKey.key")]
[assembly: AssemblyKeyName("")]